apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taller-diego-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/LARMD-2/taller-diego-gitops.git'
    targetRevision: HEAD
    path: . 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true